### ISSUE TITLE
Question and Favor

### ISSUE THREAD

**Issue by dylanvorster** [woodenconsulting/react-js-diagrams#1]
Hi there, while I'm thrilled that you are using the library, would you kindly just perhaps update your Readme as to indicate that this library is really a fork and maybe provide a URL to the original project. You also published this on NPM and now its really confusing because there are 2 versions of this library floating around and it looks like there are 2 separate authors. This would normally not be an issue, but because my project is so young, and is finally starting to gather some support, I would highly appreciate it.

**Comment by woodenconsulting** [comment]
Hey @dylanvorster thanks for reaching out. My apologies on the readme, I just updated it and republished on npm along with a link back. I'll be doing more updates in the coming days, but the confusion should be cleared up. Thanks again for your awesome work!
