### ISSUE TITLE
Help with importing

### ISSUE THREAD

**Issue by master369** [woodenconsulting/react-js-diagrams#11]
How can i import your diagram component in my project. React-js-diagrams i installed. What i should I do next? 
I try 
import * as RJD from 'react-js-diagrams'; 
    <RJD.DiagramWidget  />;
And console shows me error  TypeError: Cannot read property 'getDiagramModel' of undefined.
Сan you write a detailed installation documentation?

**Comment by Aequitas737** [comment]
Same issue here
