### ISSUE TITLE
Question regarding how to use

### ISSUE THREAD

**Issue by Manuel83** [woodenconsulting/react-js-diagrams#8]
First of all, thank you for creating this project. I have one question.

How can I fix the CSS issues? How can I import the basic css reqired for this lib?

I just imported
 
import * as RJD from 'react-js-diagrams';

![image](https://user-images.githubusercontent.com/5859486/27006645-c5124ec8-4e39-11e7-89c0-59fc63c65478.png)

**Comment by woodenconsulting** [comment]
@Manuel83 - This lib uses SASS; you can copy the scss file into your project [from the repository](https://github.com/woodenconsulting/react-js-diagrams/blob/master/src/sass.scss), or rewrite it in LESS, CSS, etc.; it isn't that large. I'm closing this for now, but if you have more questions please feel free to reopen.
